backend/README.md

- Item 1
- Primary:
- Secondary:

[DOCS] small README updates

---

app/package-lock.json
app/package.json
app/src/app/components/Map.tsx
app/src/app/components/sidebar/GerryDBViewSelector.tsx
app/src/app/components/sidebar/ResetMapButton.tsx
app/src/app/components/sidebar/Sidebar.tsx
app/src/app/components/sidebar/charts/HorizontalBarChart.tsx

- Pull in horizontal bar chart from #36
- Misc quality of life improvements
- Disable reset map for now until reset map endpoint (#38) is available
- Secondary: @bailliekova

Add horizontal bar chart back in from #36

---

.github/workflows/fly-deploy-api.yml
.github/workflows/fly-deploy-app.yml
app/.gitignore
app/Dockerfile
app/next.config.mjs
app/package-lock.json
app/package.json
app/sentry.client.config.ts
app/sentry.edge.config.ts
app/sentry.server.config.ts
app/src/app/api/sentry-example-api/route.ts
app/src/app/global-error.tsx
app/src/app/sentry-example-page/page.tsx
app/src/instrumentation.ts

- Used sentry wizard to set up FE error monitoring
- Add GHA to deploy on merge to main (Fixes #50)
- Update fly deployment `Dockerfile` to run w/ sentry
- Secondary:

Configure sentry for FE

---

app/fly.toml
backend/fly.toml

Bump min machines

---

.github/workflows/fly-deploy-api.yml
.github/workflows/fly-deploy-app.yml

run deploys concurrently in separate groups

---

app/src/app/components/sidebar/charts/HorizontalBarChart.tsx

- Item 1
- Primary:
- Secondary:

Fix build: handle null map metrics again

---

app/src/app/components/sidebar/BrushSizeSelector.tsx

- No wrap on "Brush size" label

Adjust brush size selector style

---

app/.env.dev
app/.env.docker
app/.env.production

- Fixes #130
- Secondary: @nofurtherinformation @mapmeld

Pull tiles from s3

---

.github/workflows/fly-deploy-pr.yml

- Fixes #135 
- Primary:
- Secondary:

update token name

---

.github/workflows/fly-deploy-pr.yml
app/src/app/utils/events/mapEvents.ts

- Fixes #131 
- Fixes #135 
- Secondary: @nofurtherinformation @mapmeld

Paint doest highlight in middle of geo

---

.github/workflows/fly-deploy-pr.yml
app/.env.production
app/Dockerfile
backend/fly.toml

- Trying to fix env vars in prod, which are broken
- Also trying to fix deletion of apps on merge
- Fixes #86 
- Primary:
- Secondary:

Don't use docker env vars – breaking prod I think

---

.github/workflows/fly-deploy-pr.yml

- Item 1
- Primary:
- Secondary:

Don't recreate apps on close after destroy

---

app/src/app/components/sidebar/MapModeSelector.jsx

- Item 1
- Primary: @nofurtherinformation @mariogiampieri 

should disable shatter button if not shatterable map

---

app/.prettierrc.js
app/package-lock.json
app/package.json

A small PR for JS code styling 
- Add airbnb prettier config defaults (mostly sane)
- Can be extended in `.prettierrc.js`

Add airbnb prettier config

---

app/src/app/utils/events/mapEvents.ts

Stop painting on mouse out/leave

---

backend/app/models.py
backend/app/utils.py
backend/cli.py
backend/tests/test_utils.py

- Add CLI command and utility function to update a DistrictrMap
- Refactor CLI to use session contextmanager and session decorator
- Primary: @mariogiampieri @bailliekova @nofurtherinformation 

Add CLI command and utility function to update a DistrictrMap

---

app/src/app/components/sidebar/Evaluation.tsx
app/src/app/store/mapStore.ts
app/src/app/utils/api/apiHandlers.ts
app/src/app/utils/api/queries.ts
app/src/app/utils/summaryStats.ts

- Add FE implementation of P4 summary
- There's probably a much nicer way to type this stuff but I didn't have time to think it through all the way and this works
- Primary: @nofurtherinformation @mariogiampieri 
- Secondary:
Confirming this gives P4 views which are pop balanceable

Add P4 Summary

---

app/src/app/components/sidebar/ColorPicker.tsx
app/src/app/components/sidebar/Layers.tsx
app/src/app/components/sidebar/ZoneLockPicker.tsx
app/src/app/store/mapStore.ts

- Clearer lock and unlock all
- Unlock on break
- Secondary:

Enhance lock and fix issues

---

app/src/app/components/Map.tsx
app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationChart.tsx
app/src/app/store/idCache.ts
app/src/app/utils/events/mapEvents.ts
app/src/app/utils/helpers.ts

Bugfix PR with two main fixes: on click events and paint by county
- Enhance paint by county to do population bar stuff
- In turn, fixes paint by county not logging properly
- Onclick events weren't properly add zone assignments either
- Enhances the ID cache to store properties

Paint fixes

---

app/src/app/utils/events/mapEvents.ts

Change property accessed for statefp in county

Fix county filter

---

pipelines/simple_elt/main.py

- Updates pipeline tile gen args to remove slivers, fixes #70 
- Thanks to @nofurtherinformation for getting this started
- As part of this PR I updated the prod layers using the management CLI
- Primary: @nofurtherinformation 

Remove slivers

---

.github/workflows/fly-deploy-pr.yml

- Adjust default memory of postgres machine 4GB -> 1GB, [saving $15.01](https://fly.io/docs/about/pricing/) per PR app per month.
- TLDR it is (annoyingly) not possible to create a fly postgres cluster specifying the memory size on startup. Instead it is recommended to start with the closest preset (4GB for `shared-cpu-2x`) and then [adjust subsequently](https://fly.io/docs/postgres/managing/scaling/). It _is_ possible to [set the default machine memory in the `fly.toml` config](https://community.fly.io/t/unexpected-ram-increase-in-shared-cpu-1x-after-deployment/17134) but since we are forking from prod (incl. its configs) this would mean prod has to be set up with fewer resources.
- Secondary: @nofurtherinformation

Update PR DB machine memory

---

app/src/app/store/mapStore.ts
app/src/app/utils/api/apiHandlers.ts

[TEST] Minimal partial assignment

---

app/src/app/store/mapEditSubs.ts

dont send empty assignments

---

app/src/app/components/sidebar/PopulationPanel/PopulationPanel.tsx
app/src/app/store/mapRenderSubs.ts

A couple bugs came up after the UI revamp merge, this resolves:
- Unassigned not displaying correctly
- Issue with an infinite loop / max call stack exceeded issue

Bugfixes - UI Merge

---

.github/workflows/fly-deploy-pr.yml
backend/app/core/config.py
backend/app/main.py

- Differentiate between prod and qa envs for sentry. This should provide less noise and more signal in our debugging.
- Primary: @nofurtherinformation @mariogiampieri
- Secondary: @districtr/districtr-reboot

PR deploys are QA

---

.gitignore
backend/load_data.py
docker-compose.yml
sample_data/config.json

Load data script update

---

backend/app/alembic/versions/f36266d50cf7_create_pce_index.py
backend/app/main.py

Reworks the get assignments query slightly and adds an index to massively speed things up.

Faster get assignments

---

.github/workflows/fly-deploy-pr.yml
app/src/app/components/sidebar/MapValidation/Contiguity.tsx
app/src/app/store/unassignedFeatures.ts

- Don't retry contiguity on failure
- Show detailed error message to user from contig endpoint if available
- Primary: @nofurtherinformation 

Contiguity follow up bug fixes

---

app/src/app/map/page.tsx
app/src/app/store/mapStore.ts
app/src/app/store/subscriptions.tsx
app/src/app/utils/api/queries.ts
app/src/app/utils/api/queryParamsListener.ts
app/src/app/utils/demography/demographyCache.ts
app/src/app/utils/map/mapRenderSubs.ts

A couple fixes
- Fixes for return to tab bugs 
- Extra safety on populaiton bars

Post choropleth bug fixes

---

backend/app/alembic/versions/fa7d5c356d1f_districtr_map_slug.py

Adds shatter parent UDF
- Secondary:

Bugfix -- add shatter parent UDF to migration

---

backend/Dockerfile.dev
backend/app/alembic/versions/b04f5bed1e48_faster_connected_component_bboxes.py
backend/app/contiguity/main.py
backend/app/main.py
backend/app/sql/get_block_zone_assignments_bboxes.sql
backend/app/utils.py
backend/cli.py
backend/management/load_data.py
backend/requirements.txt
backend/tests/test_main.py

- Improves #322 , addressing perf (and db OOM issues). Better but still not an awesome ux imo
- Does this mainly by (1) moving the reprojection to the last step so it's only run on the final bbox coords and (2) not dipping back into the db and just iterating over the results in python. Not a terribly attractive/satisfying implementation tbh but more than twice as fast in most cases and <1s
- Primary: @mariogiampieri @nofurtherinformation 
- Secondary: @districtr/districtr-reboot

Fixes #322 - Faster connected component bboxes

---

.gitignore
app/src/app/components/Topbar.tsx
app/src/app/components/sidebar/MapValidation/Contiguity.tsx
app/src/app/components/sidebar/MapValidation/ContiguityDetail.tsx
app/src/app/store/mapStore.ts

Additional FE polishes.
- Resolves #276 
- Works on #343 - adds state to track when a zone has been painted, and if it has changed since the last contiguity check the icon becomes a question mark to avoid presenting stale data
- Secondary:

Fe Polish Part 2

---

backend/app/models.py
backend/management/configs/indiana_towns.yaml
backend/management/load_data.py

Indiana Towns backend config

---

app/src/app/components/Topbar.tsx

This snuck by during the block import

Remove double status button

---

app/package-lock.json
app/package.json
app/src/app/(static)/about/page.tsx
app/src/app/(static)/contact/page.tsx
app/src/app/(static)/data/page.tsx
app/src/app/(static)/guide/page.tsx
app/src/app/(static)/layout.tsx
app/src/app/(static)/page.tsx
app/src/app/(static)/place/[slug]/page.tsx
app/src/app/(static)/places/page.tsx
app/src/app/(static)/rules/page.tsx
app/src/app/(static)/tag/[slug]/page.tsx
app/src/app/(static)/tags/page.tsx
app/src/app/(static)/updates/page.tsx
app/src/app/components/Static/Footer.tsx
app/src/app/components/Static/Interactions/CreateButton.tsx
app/src/app/globals.css
app/src/app/layout.tsx
prototypes/v1/app/next.config.js

- #372 
- #373 
- #374
- #377 
- #379
- Primary: @cdonnay 
- Secondary:

UI fixes and copy updates

---

app/src/app/(static)/group/[slug]/page.tsx
app/src/app/utils/api/apiHandlers/getGroup.ts

- Use env variable for the api request
- Small FE cleanup
- Primary: @mapmeld 
- Secondary:

Group page fix

---

app/src/app/components/Toolbar/Settings.tsx
app/src/app/components/Toolbar/ToolButtons.tsx
app/src/app/components/Toolbar/ToolControls.tsx
app/src/app/components/Toolbar/Toolbar.tsx
app/src/app/components/sidebar/ToolbarInSidebar.tsx
app/src/app/store/chartStore.ts
app/src/app/store/toolbarStore.ts

- #405 
- #414 
- Adds smarter snapping/rotating logic to the toolbar 
- Primary: @mapmeld 
- Secondary: @raphaellaude

New defaults

---

app/src/app/utils/ParquetWorker/parquetWorker.ts

Update path from `dev` to `tilesets` for point data.
We could rename this to something like `geodata` but for now just cleaning it up from `dev` is probably good

Update point data path

---

.github/workflows/fly-deploy-app.yml

The prod deploy missed a variable

[HOTFIX] Fix deploy environment

---

app/src/app/(static)/tag/[slug]/page.tsx
app/src/app/components/Cms/RichTextEditor/extensions/CommentSubmissionForm/FormNode.ts
app/src/app/components/Cms/RichTextEditor/extensions/CommentSubmissionForm/FormNodeView.tsx
app/src/app/components/Cms/RichTextEditor/extensions/HeaderSecondTierNav/HeaderSecondTierNav.tsx
app/src/app/components/Cms/RichTextEditor/extensions/MapCreateButtons/MapCreateButtons.tsx
app/src/app/components/Cms/RichTextEditor/extensions/MapCreateButtons/MapCreateButtonsNode.tsx
app/src/app/components/Cms/RichTextEditor/extensions/MapCreateButtons/MapCreateButtonsNodeView.tsx
app/src/app/components/Cms/RichTextEditor/extensions/PlanGallery/PlanGallery.tsx
app/src/app/components/Cms/RichTextEditor/extensions/PlanGallery/PlanGalleryNode.tsx
app/src/app/components/Cms/RichTextEditor/extensions/PlanGallery/PlanGalleryNodeView.tsx
app/src/app/components/Cms/RichTextEditor/extensions/extensionUtils.ts
app/src/app/components/Forms/AcknowledgementField.tsx
app/src/app/components/Forms/CommentFormTagSelector.tsx
app/src/app/components/Forms/CommentSubmissionForm.tsx
app/src/app/components/Forms/MapSelector.tsx
app/src/app/components/Forms/TagSelector.tsx
app/src/app/components/RichTextRenderer/CustomRenderers/DomNodeRenderers.tsx
app/src/app/components/RichTextRenderer/RichTextRenderer.tsx
app/src/app/components/Static/Interactions/CreateButton.tsx
app/src/app/components/sidebar/MapValidation/Contiguity.tsx
app/src/app/hooks/useCmsEditorConfig.tsx
app/src/app/hooks/useMapModules.tsx
app/src/app/hooks/useRecaptcha.tsx
app/src/app/store/formState.ts

- Various fixes and clean up
- Add map create buttons CMS component
- Primary:
- Secondary:

Tag page enhancements

---

backend/app/alembic/env.py
backend/app/main.py
backend/app/models.py

- Testing out an idea: if you inline the districtr map uuid, will the join on parent child edges correctly pick out the single partition to use?
- Primary: @nofurtherinformation 
- Secondary:

Optimize get assignments
