districtr/districtr-v2

.github/workflows/test-backend.yml, backend/.dockerignore, backend/app/core/config.py
- Just set all postgres env vars as secrets individually. It's crude / duplicative but more fullproof, plus matches the `.env` file layout.
- As such, in settings we can make all of the env vars required, which simplifies the control flow across the app
- Primary: @bailliekova 
=> Simplify handling of postgres env vars

app/src/app/components/Map.tsx, app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
Thanks to Raphael for helping me get an interactive map set up on my machine
Here's my proposed fix for the Recharts bar chart; their default types for XAxis and YAxis were causing some rendering issues.  This updates the hidden YAxis and adds a tooltip when hovering over the chart.
I also added some code for controlling the scroll zoom for mouse + trackpad, I don't have proof if this does anything here, but the UI/UX felt a little different from Districtr so I was trying to slow down.
=> Recharts fix

app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
Updates the previous recharts PR #78 with types for TypeScript build:
- label types for the custom tooltip component
- revert changes to `useMapStore` syntax - typing was too verbose
- sort `mapMetrics.data` by zone before rendering the chart
- ALSO reuse `numberFormat.format` in the custom tooltip component
=> Amend types in recharts PR

app/src/app/api/apiHandlers.ts, app/src/app/components/Map.tsx, app/src/app/components/sidebar/MapModeSelector.jsx, app/src/app/components/sidebar/Sidebar.tsx, app/src/app/constants/types.ts, app/src/app/store/mapStore.ts, app/src/app/utils/events/handlers.ts, app/src/app/utils/events/mapEvents.ts, backend/app/alembic/versions/09d011c1b387_zones_can_be_null.py, backend/app/main.py, backend/app/models.py, backend/tests/test_main.py
Concepts:
- enable Eraser button
- when `activeTool === "eraser"`, we see the hover-highlight on the map
- clicking in eraser mode stores zoneAssignment = null in frontend parts of the app
- in eraser mode, we call `patchEraseAssignments` to delete rows; server confirms that zone assignment is null/None.
- `patchUpdateAssignments` has a filter to store only non-eraser areas on the server
Thoughts:
- now that I understand how `patchEraseAssignments` needs to work on the server, maybe I should rename it to delete
- old zone: null assignments should be cleared on the frontend after they've been successfully passed to the server
=> Eraser feature!

.github/workflows/fly-deploy-pr.yml, app/fly.toml, app/src/app/components/sidebar/GerryDBViewSelector.tsx, app/src/app/components/sidebar/MapModeSelector.jsx, app/src/app/components/sidebar/RecentMapsModal.tsx, app/src/app/constants/types.ts, app/src/app/store/mapRenderSubs.ts, app/src/app/utils/events/mapEvents.ts, app/src/app/utils/helpers.ts, backend/fly.toml
- Fixes #134 and #133
- Secondary: @mapmeld @nofurtherinformation
=> Shatter tool

app/src/app/components/sidebar/ResetMapButton.tsx
#168 
- Adds dialog to confirm reset
- Primary: @raphaellaude
=> Alert dialog for map reset

app/src/app/components/sidebar/ZonePicker.tsx, app/src/app/store/mapRenderSubs.ts
#176 
- Bug fix
- Adds the following logic
When setting locked features after a zone assignment change, app will check if the zone assignment is:
- Included in the locked zones
- Not null
- When locked areas did not change, was the feature already in the locked features
- When locked areas did change, was the zone previously locked and is now unlocked and was the feature already in the locked features
This allows individually locked features to remain locked while doing other business, AND allows individual features in a locked zone to be unlocked and painted 
=> Fix logic for checking individual locked areas

app/src/app/components/sidebar/Layers.tsx, app/src/app/constants/layers.ts, app/src/app/store/mapRenderSubs.ts, app/src/app/store/mapStore.ts, app/src/app/store/types.ts
#169 
- Adds option to highlight un assigned geometries to make them easier to find and paint
- Primary: @mapmeld 
- Secondary: @raphaellaude
=> Highlight unassigned geographies

app/src/app/constants/layers.ts
I thought this condition was working but small bug got introduce - broken parents need should be able to be highlighted and focused for certain tasks, so the check if their broken needs to be part of the highlight unassigned areas check, not before.
- Primary: @raphaellaude
=> Highlight bugfix

app/src/app/constants/layers.ts, app/src/app/store/mapStore.ts
Bug introduced in refactor that missed removing the maplibre source on remove layers. Current refactor is more readable for future changes.
- In `removeBlockLayers` adds a second loop for sources that calls `removeSource`
- A future refactor should centralize layer and source manipulations in a single class or store to make it more consistent and ergonomic 
- Primary: @raphaellaude
=> Bugfix - remove source

app/src/app/components/Map.tsx, app/src/app/components/sidebar/PaintByCounty.tsx, app/src/app/constants/layers.ts, app/src/app/store/idCache.ts, app/src/app/store/mapRenderSubs.ts, app/src/app/store/mapStore.ts, app/src/app/store/types.ts, app/src/app/utils/events/mapEvents.ts, app/src/app/utils/helpers.ts
Instead of painting by county using features, this PRs drafts a method of caching all IDs and then filtering based on those
- Cache IDs of features on `data` in the map
- When painting by county, search those IDs
=> Paint by county with ID instead of features

app/src/app/components/sidebar/ZoneLockPicker.tsx, app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
Adds top-to-bottom deviation and lock icon
=> Chart enhancements

app/src/app/components/sidebar/Evaluation.tsx, app/src/app/components/sidebar/MapModeSelector.jsx, app/src/app/components/sidebar/PaintByCounty.tsx, app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
Small final text updates ahead of user testing
=> Text Updates

app/src/app/store/mapEditSubs.ts, app/src/app/store/mapStore.ts, app/src/app/utils/api/apiHandlers.ts, app/src/app/utils/api/mutations.ts, app/src/app/utils/api/queries.ts
We get in some weird states where the async nature of the population and updates can get out of sync with the frontend. This shows as population bars jumping around when the server is under load. 
- Adds abort controllers to update and zone population queries
- Increase debounce on zone updates
- Track last zone updates with a hash to eliminate duplicate zone updates (eg. on mouse out, painting stops and a zone update is triggered even if no features have been updated)
- Secondary:
=> Better FE request management 

app/src/app/components/Map.tsx, app/src/app/utils/events/mapEvents.ts
Bug was repeatable: having the cursor leave the map while painting leaves that area shaded until you resume painting, this can be a longer time if you change to the move cursor
This might have caused a colors issue here:
Proposed solution: `useHoverStore` gives us a function to clear the hover features; this requires a short timeout to avoid the map re-selecting these features
=> Hovered features should reset after mouse leaves the map

app/src/app/components/sidebar/Layers.tsx, app/src/app/constants/basemapLayers.ts, app/src/app/store/mapRenderSubs.ts, app/src/app/store/mapStore.ts, app/src/app/store/types.ts
Makes county labels more prominent. Adds toggle option
- Toggle on/off to make county labels more prominent from feedback last week
=> County label enhancement

app/src/app/components/sidebar/DataPanels.tsx, app/src/app/components/sidebar/Layers.tsx, app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationChart.tsx, app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationLabels.tsx, app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationTooltip.tsx, app/src/app/components/sidebar/PopulationPanel/PopulationPanel.tsx, app/src/app/components/sidebar/PopulationPanel/PopulationPanelOptions.tsx, app/src/app/components/sidebar/Sidebar.tsx, app/src/app/store/mapStore.ts, app/src/app/utils/events/mapEvents.ts
Various requested organization and quality of life enhancements
This PR integrates the following feedback from Moon:
- move "Highlight unassigned units" and "Show population tooltip" out of data layers -- makes more sense in the population tab
- add a counter for unassigned population
- the hover-over on the population bars would be fine with just distance to ideal, doesn't need distance to max
- stash the "target deviation from ideal" feature in the gear drop-down, i.e., treat it as an advanced feature
- the user should start in the population tab when they pick a geography.  (Now I think it starts in data layers.)
- the tool remembers a lot of settings from your last map when you start a new map, such as whether the tooltip is on, whether you're in zoom mode on population bars, what …
=> Qol organization changes

app/src/app/utils/api/mutations.ts
We are now using a slightly redundant 'loadedMapId' piece of state to avoid re-running certain subscriptions and functions, especially when tabbing in and out.
A small bug occurs when you create a new map, then return to the immediately previous map via Recents. This PR makes the new document create mutation change the loadedMapId in the state, which resolves the issue
=> [bugfix] Stale loaded map ID on new document

app/src/app/store/mapStore.ts, app/src/app/utils/api/apiHandlers.ts, app/src/app/utils/api/queries.ts
Fixes an issue where map loads would not properly initialize with empty assignments
=> Bugfix for assignment load validation logic

app/src/app/components/sidebar/ColorPicker.tsx
I noticed the same bug as #205 some time ago. If I remember right, it was when we added `num_districts` to the DB, so older maps had `null ?? 0` districts. This updates the null count fallback to be 4 districts.
=> Update fallback for null num_districts [fixes #205]

app/src/app/components/sidebar/PopulationPanel/PopulationPanel.tsx, app/src/app/store/mapEditSubs.ts, app/src/app/store/mapStore.ts, app/src/app/utils/api/queries.ts, app/src/app/utils/events/mapEvents.ts
There are a few bugs with population while painting that make it feel unreliable.
- Changes break/healing to be a non-temporal action so that population properly incorporates
- Adds a throttle to map click events to prevent double paint events at the block level
- Primary: @mapmeld 
- Secondary: @raphaellaude
=> Population bars while painting bug fixes (part 1)

app/src/app/components/Cms/ContentEditor/ContentEditor.tsx, app/src/app/components/Map/HighlightOverlayLayerGroup.tsx, app/src/app/components/Map/MetaLayers.tsx, app/src/app/constants/layers.ts, app/src/app/utils/GeometryWorker/geometryWorker.ts, app/src/app/utils/GeometryWorker/geometryWorker.types.ts, backend/app/cms/main.py, backend/app/cms/models.py
This PR improves the zone label positioning.
- Previous work to position zone labels used geometric dissolves / unions and centroids, which was slow (2000-3000ms), but pretty good
- To optimize this, we started using random points (~20-100ms), but that was kind of annoying when points on or near the edges were selected
- This approach instead compromises by making a low res raster of the map and choosing a valid point based on the raster image; this is pretty much as good as the first method, but much faster (~30-60ms)
- Secondary:
=> Better zone number labels

app/src/app/layout.tsx, app/src/app/utils/api/apiHandlers/types.ts
This replaces NextJS's static metadata feature with its `generateMetadata` async function, allowing the title and description of the page and its social media / opengraph preview to use a map's name, description, and number of districts.
- I suggest the Districtr paintbrush logo as the social media image until we add #314 to make individual thumbnail URLs
- Replaces description "Districtr reboot" with "Create districting maps"
- On OpenGraph where we already have siteName "Districtr 2.0" and the Districtr logo, the title can be "Get Started" on general pages like the homepage or /map
- On individual maps the title would be "3 districts - NAME" or "3 districts - Shared Map"
- On individual maps the description would be from map metadata or "Create districting maps"
Notes:
- removes a …
=> Use maps metadata in title/description

app/src/app/components/sidebar/MapValidation/Contiguity.tsx
Fixes #313
Loads colorScheme from mapStore to allow custom colors
I did a `git grep` to check if other files still use `colorScheme` from `constants/colors `, and others already have been updated to `import {colorScheme as DefaultColorScheme}`
=> Contiguity tool loads custom colorScheme

backend/management/load_data.py
From a fresh install, the load data script had a couple breaking errors:
1. When making gerrydb views, the views not committed before building which cause the geo index to fail and mess up other stuff down the line
2. When makign the districtrmap view, the view was not committed before trying to make parent child edges
=> Bugfix: load data

app/src/app/components/Toolbar/ColorPicker.tsx, app/src/app/store/mapStore.ts, app/src/app/utils/colors.ts
- #376 
- Extends the map document color palette or default color palette on load
- Uses Peters procedural color generation strategy
- Secondary:
=> Extend color palette

app/src/app/components/Map/MetaLayers.tsx, app/src/app/components/Toolbar/Settings.tsx, app/src/app/components/Topbar.tsx, app/src/app/store/mapStore.ts, app/src/app/store/types.ts, app/src/app/utils/GeometryWorker/geometryWorker.ts, app/src/app/utils/GeometryWorker/geometryWorker.types.ts, app/src/app/utils/events/mapEvents.ts
There are a couple issues with maps that are only parent geographies with no child layer. This 
- Allow showing population numbers (eg. #325)
=> Enable population numbers for all geometries

app/src/app/utils/api/queries.ts
There is an edge case where upon returning to tab that has slept, the subscription re-subscribes and loads stale data. There is never a case where we want stale document data to load in temporarily, since it has `updated_at` and `access`/`edit` state attached to it, which can change on re-focus
- Remove stale time from map document query
- Remove placeholder data from map document query
- Secondary:
=> Bugfix: stale document

app/src/app/(static)/group/[slug]/page.tsx, backend/app/thumbnails/main.py, backend/tests/test_main.py, backend/tests/test_thumbnails.py
A DistrictrMap can now have a preview / thumbnail image which shows the blocks which make up a blank map:
- Backend adds a variant of the thumbnail-generator function, this works without a Document, makes a larger image, and prints yellow-tan blocks on top of a light color background
- Frontend has an updated thumbnail image path, same fallback images
- Includes test
- CSS fixes my data import / scripting mistake where places such as Tell City were showing up as "Tell city, IN"
I had the light color background be a random selection of light blue, green, grey, or purple; I would consider different colors, or printing a transparent background so the background color could be done in CSS. Without colors, I worry this would be too monotonous to have every map looking the same, and we …
=> On group page, DistrictrMaps have thumbnails

app/src/app/utils/demography/demographyCache.ts
Adds an additional check to make sure demography table contains no duplicate entries
=> [HiGH] Ensure path is deduped on table updates

app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationChart.tsx
Small fix to silence warning
When loading into a map, the chart would try to render before the parentSize hook has the width, firing some SVG warnings.
=> Stop chart from rendering before parent is ready

app/src/app/utils/api/apiHandlers/getAvailableDistrictrMaps.ts, backend/app/main.py
Currently we have a few pages (places, tags) that just get the full list of views and filter for the correct ones. Longer term we need a better way to query specific view information but for now we can use the same parts and just expand the limit on the amount of data returned. There is a unit of work here to move away from the long list in general, but to get the place pages working again for the short term, this will work.
=> [Hotfix] Increase views cap to 1000
